name: eslint-auto-fix

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./function/
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p /home/runner/.npm
      continue-on-error: true

    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: npm install
      run: npm install
    - name: npm install eslint
      run: npm install eslint -g
    - name: run eslint fix
      run: eslint "./src/**.ts" --fix

